#pragma once

#include <iostream>
#include <string>

using namespace std;

class Student {
private:
    const static int NUM_HOMEWORKS = 10;
    const static int NUM_QUIZZES = 5;
    const static int NUM_PROJECTS = 1;
    const static int NUM_MIDTERMS = 1;
    const static int NUM_MIDTERM2S = 1;
    const static int NUM_FINALS = 1;

    const static int NUM_GRADES = NUM_HOMEWORKS + NUM_QUIZZES + NUM_PROJECTS + NUM_MIDTERMS + NUM_FINALS;

    string name;
    int id;
    int homeworkGrades[NUM_HOMEWORKS];
    int quizGrades[NUM_QUIZZES];
    int projectGrades[NUM_PROJECTS];
    int midtermGrades[NUM_MIDTERMS];
    int midterm2Grades[NUM_MIDTERM2S];
    int finalGrades[NUM_FINALS];

public:
    // TODO: A student can print their own grades
    // TODO: I think the GradeBook may need to get a student's ID when searching
    void InitFromLine(string line);
    void PrintGrades();

    //Getters and setters generated by Eclipse IDE
	const int* getHomeworkGrades() const;
	const string& getName() const;
	void setName(const string& name);
	const int* getQuizGrades() const;
	const int* getTestGrades() const;
	int getId() const;
	void setId(int id);
	const int* getFinalGrades() const;
	const int* getMidtermGrades() const;
	const int* getMidterm2Grades() const;
	const int* getProjectGrades() const;
};
